export const jobs = [
  {
    id: 1,
    title: "Medical Check-up",
    requestDate: "28 Mar 2020 07:50 PM",
    budgetRate: "N 1,500 / hr",
    jobType: "Task Master",
    posted: "Admin",
    location: "Lagos",
    bidAmount: 0.00,
  },
  {
    id: 2,
    title: "Medical Check-up",
    requestDate: "28 Mar 2020 07:50 PM",
    budgetRate: "N 1,500 / hr",
    jobType: "Task Master",
    posted: "Admin",
    location: "Lagos",
    bidAmount: 0.00,
  },
  {
    id: 3,
    title: "Medical Check-up",
    requestDate: "28 Mar 2020 07:50 PM",
    budgetRate: "N 1,500 / hr",
    jobType: "Task Master",
    posted: "Admin",
    location: "Lagos",
    bidAmount: 0.00,
  },
  {
    id: 4,
    title: "Medical Check-up",
    requestDate: "28 Mar 2020 07:50 PM",
    budgetRate: "N 1,500 / hr",
    jobType: "Task Master",
    posted: "Admin",
    location: "Lagos",
    bidAmount: 0.00,
  },
  {
    id: 5,
    title: "Medical Check-up",
    requestDate: "28 Mar 2020 07:50 PM",
    budgetRate: "N 1,500 / hr",
    jobType: "Task Master",
    posted: "Admin",
    location: "Lagos",
    bidAmount: 0.00,
  },
  {
    id: 6,
    title: "Medical Check-up",
    requestDate: "28 Mar 2020 07:50 PM",
    budgetRate: "N 1,500 / hr",
    jobType: "Task Master",
    posted: "Admin",
    location: "Lagos",
    bidAmount: 0.00,
  },
  {
    id: 7,
    title: "Medical Check-up",
    requestDate: "28 Mar 2020 07:50 PM",
    budgetRate: "N 1,500 / hr",
    jobType: "Task Master",
    posted: "Admin",
    location: "Lagos",
    bidAmount: 0.00,
  },
  {
    id: 8,
    title: "Medical Check-up",
    requestDate: "28 Mar 2020 07:50 PM",
    budgetRate: "N 1,500 / hr",
    jobType: "Task Master",
    posted: "Admin",
    location: "Lagos",
    bidAmount: 0.00,
  },
  {
    id: 9,
    title: "Medical Check-up",
    requestDate: "28 Mar 2020 07:50 PM",
    budgetRate: "N 1,500 / hr",
    jobType: "Task Master",
    posted: "Admin",
    location: "Lagos",
    bidAmount: 0.00,
  },
]